name = "AdaptiveAIS"
uuid = "6fb7a829-3708-49bf-b99d-2469cbd06686"
authors = ["Zuheng Xu"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
